# .cpanel.yml
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/ggabank_app
    - echo "Copying files to $DEPLOYPATH" >> $DEPLOYPATH/deployment.log
    - /bin/cp -r * $DEPLOYPATH >> $DEPLOYPATH/deployment.log 2>&1
    - cd $DEPLOYPATH
    - echo "Copying .env.example to .env" >> deployment.log
    - cp .env.example .env >> deployment.log 2>&1
    - echo "Installing Composer dependencies" >> deployment.log
    - composer install --no-dev --prefer-dist >> deployment.log 2>&1
    - echo "Installing npm dependencies" >> deployment.log
    - npm install >> deployment.log 2>&1
    - echo "Building frontend assets" >> deployment.log
    - npm run production >> deployment.log 2>&1
    - echo "Generating application key" >> deployment.log
    - php artisan key:generate >> deployment.log 2>&1
    - echo "Running database migrations" >> deployment.log
    - php artisan migrate --force >> deployment.log 2>&1
    - echo "Setting file permissions" >> deployment.log
    - chown -R username:username $DEPLOYPATH >> deployment.log 2>&1
    - chmod -R 755 $DEPLOYPATH >> deployment.log 2>&1
    - chmod -R 775 $DEPLOYPATH/storage >> deployment.log 2>&1
    - chmod -R 775 $DEPLOYPATH/bootstrap/cache >> deployment.log 2>&1
    - echo "Deployment completed" >> deployment.log
