# .cpanel.yml
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/ggabank_app
    - /bin/cp -r * $DEPLOYPATH
    - cd $DEPLOYPATH
    - cp .env.example .env
    - composer install --no-dev --prefer-dist
    - npm install
    - npm run production
    - php artisan key:generate
    - php artisan migrate --force
    - chown -R username:username $DEPLOYPATH
    - chmod -R 755 $DEPLOYPATH
    - chmod -R 775 $DEPLOYPATH/storage
    - chmod -R 775 $DEPLOYPATH/bootstrap/cache
